# Generated by Django 6.0.5 on 2026-08-25

from django.db import migrations, models


def copy_sistema_categoria(apps, schema_editor):
    tables = schema_editor.connection.introspection.table_names()
    if 'sistema_categoria' not in tables:
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            INSERT OR IGNORE INTO categoria_categoria (id, nome, descricao, tipo_locacao)
            SELECT id, nome, descricao, tipo_locacao
            FROM sistema_categoria
            """
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('tipo_locacao', models.CharField(max_length=80)),
            ],
        ),
        migrations.RunPython(copy_sistema_categoria, migrations.RunPython.noop),
    ]
