# Generated by Django 6.0.5 on 2026-08-25

import django.db.models.deletion
from django.db import migrations, models


def copy_sistema_locacao(apps, schema_editor):
    tables = schema_editor.connection.introspection.table_names()

    with schema_editor.connection.cursor() as cursor:
        if 'sistema_locacao' in tables:
            cursor.execute(
                """
                INSERT OR IGNORE INTO locacao_locacao (
                    id,
                    nome,
                    descricao,
                    preco_diaria,
                    capacidade_maxima,
                    endereco,
                    local,
                    fk_categoria_id
                )
                SELECT
                    id,
                    nome,
                    descricao,
                    preco_diaria,
                    capacidade_maxima,
                    endereco,
                    local,
                    fk_categoria_id
                FROM sistema_locacao
                """
            )

        if 'sistema_imagem' in tables:
            cursor.execute(
                """
                INSERT OR IGNORE INTO locacao_imagem (
                    id,
                    url,
                    descricao,
                    ordem,
                    principal,
                    fk_locacao_id
                )
                SELECT id, url, descricao, ordem, principal, fk_locacao_id
                FROM sistema_imagem
                """
            )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('preco_diaria', models.FloatField()),
                ('capacidade_maxima', models.IntegerField()),
                ('endereco', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=120)),
                ('fk_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locacoes', to='categoria.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('ordem', models.IntegerField(default=1)),
                ('principal', models.BooleanField(default=False)),
                ('fk_locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='locacao.locacao')),
            ],
        ),
        migrations.RunPython(copy_sistema_locacao, migrations.RunPython.noop),
    ]
