# Generated by Django on 2026-08-25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0002_copy_locacao_imagem'),
        ('locacao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagem',
        ),
    ]
