# Generated by Django 6.0.5 on 2026-09-29 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0002_delete_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='área em m²'),
        ),
        migrations.AddField(
            model_name='locacao',
            name='banheiros',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locacao',
            name='demonstracao',
            field=models.BooleanField(default=False, editable=False, verbose_name='imóvel de demonstração'),
        ),
        migrations.AddField(
            model_name='locacao',
            name='disponivel',
            field=models.BooleanField(default=True, verbose_name='disponível para locação'),
        ),
        migrations.AddField(
            model_name='locacao',
            name='preco_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='aluguel mensal'),
        ),
        migrations.AddField(
            model_name='locacao',
            name='quartos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locacao',
            name='vagas_garagem',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='vagas de garagem'),
        ),
    ]
