# Generated by Django 6.0.5 on 2026-08-25

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_sistema_usuario(apps, schema_editor):
    tables = schema_editor.connection.introspection.table_names()
    if 'sistema_usuario' not in tables:
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            INSERT OR IGNORE INTO usuario_usuario (user_ptr_id, telefone, CPF, criado_em)
            SELECT fk_user_id, telefone, CPF, criado_em
            FROM sistema_usuario
            """
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telefone', models.CharField(max_length=20)),
                ('CPF', models.CharField(max_length=11, unique=True)),
                ('criado_em', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RunPython(copy_sistema_usuario, migrations.RunPython.noop),
    ]
