# Generated by Django 6.1 on 2026-08-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='CPF',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.BigIntegerField(),
        ),
    ]
