# Generated by Django on 2026-08-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('ordem', models.IntegerField(default=1)),
                ('principal', models.BooleanField(default=False)),
                ('fk_locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='locacao.locacao')),
            ],
        ),
    ]
