# Generated by Django on 2026-08-25

from django.db import migrations


def copy_locacao_imagem(apps, schema_editor):
    tables = schema_editor.connection.introspection.table_names()
    if 'locacao_imagem' not in tables:
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            INSERT OR IGNORE INTO imagens_imagem (
                id,
                url,
                descricao,
                ordem,
                principal,
                fk_locacao_id
            )
            SELECT
                id,
                url,
                descricao,
                ordem,
                principal,
                fk_locacao_id
            FROM locacao_imagem
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0001_initial'),
        ('locacao', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_locacao_imagem, migrations.RunPython.noop),
    ]
