# Generated by Django 6.0.5 on 2026-08-22 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('tipo_locacao', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0.0)),
                ('status', models.CharField(default='pendente', max_length=30)),
                ('metodo', models.CharField(default='pix', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('preco_diaria', models.FloatField()),
                ('capacidade_maxima', models.IntegerField()),
                ('endereco', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=120)),
                ('fk_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locacoes', to='sistema.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('ordem', models.IntegerField(default=1)),
                ('principal', models.BooleanField(default=False)),
                ('fk_locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='sistema.locacao')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('CPF', models.CharField(max_length=11, unique=True)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('fk_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField()),
                ('valor_total', models.FloatField(default=0.0)),
                ('status', models.CharField(default='pendente', max_length=30)),
                ('fk_locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='sistema.locacao')),
                ('fk_pagamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserva', to='sistema.pagamento')),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='sistema.usuario')),
            ],
        ),
    ]
