# Generated by Django 6.0.5 on 2026-08-25

import django.db.models.deletion
from django.db import migrations, models


def copy_sistema_reserva(apps, schema_editor):
    tables = schema_editor.connection.introspection.table_names()
    if 'sistema_reserva' not in tables:
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            INSERT OR IGNORE INTO reserva_reserva (
                id,
                data_entrada,
                data_saida,
                valor_total,
                status,
                fk_locacao_id,
                fk_pagamento_id,
                fk_usuario_id
            )
            SELECT
                reserva.id,
                reserva.data_entrada,
                reserva.data_saida,
                reserva.valor_total,
                reserva.status,
                reserva.fk_locacao_id,
                reserva.fk_pagamento_id,
                usuario.fk_user_id
            FROM sistema_reserva reserva
            INNER JOIN sistema_usuario usuario
                ON usuario.id = reserva.fk_usuario_id
            """
        )


def drop_sistema_tables(apps, schema_editor):
    tables = schema_editor.connection.introspection.table_names()
    old_tables = [
        'sistema_reserva',
        'sistema_imagem',
        'sistema_locacao',
        'sistema_pagamento',
        'sistema_usuario',
        'sistema_categoria',
    ]

    with schema_editor.connection.cursor() as cursor:
        for table in old_tables:
            if table in tables:
                cursor.execute(f'DROP TABLE {table}')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locacao', '0001_initial'),
        ('pagamento', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField()),
                ('valor_total', models.FloatField(default=0.0)),
                ('status', models.CharField(default='pendente', max_length=30)),
                ('fk_locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='locacao.locacao')),
                ('fk_pagamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserva', to='pagamento.pagamento')),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='usuario.usuario')),
            ],
        ),
        migrations.RunPython(copy_sistema_reserva, migrations.RunPython.noop),
        migrations.RunPython(drop_sistema_tables, migrations.RunPython.noop),
    ]
