# Generated by Django 6.0.5 on 2026-08-25

from django.db import migrations, models


def copy_sistema_pagamento(apps, schema_editor):
    tables = schema_editor.connection.introspection.table_names()
    if 'sistema_pagamento' not in tables:
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            INSERT OR IGNORE INTO pagamento_pagamento (id, valor, status, metodo)
            SELECT id, valor, status, metodo
            FROM sistema_pagamento
            """
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0.0)),
                ('status', models.CharField(default='pendente', max_length=30)),
                ('metodo', models.CharField(default='pix', max_length=50)),
            ],
        ),
        migrations.RunPython(copy_sistema_pagamento, migrations.RunPython.noop),
    ]
