# Generated by Django 6.0.5 on 2026-09-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='metodo',
            field=models.CharField(choices=[('pix', 'Pix'), ('cartao', 'Cartão')], default='pix', max_length=50, verbose_name='método de pagamento'),
        ),
    ]
